package poocft;

import com.mysql.jdbc.Connection;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


public final class mainmenu extends javax.swing.JFrame {

    
    public static final String URL = "jdbc:mysql://localhost:3306/articulos"; 
    public static final String USERNAME = "root"; 
    public static final String PASSWORD = "";
    
    public static Connection getConection() {
        Connection con = null;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(URL, USERNAME, PASSWORD);
            

        } catch (Exception e) {
            System.out.println(e);
        }
        return con;
    }
    
    DefaultTableModel model;
    PreparedStatement ps;
    ResultSet rs;
    Statement st;
    TableRowSorter trs;
    
    public mainmenu() {
        initComponents();
        cargarTabla("");
        this.setLocationRelativeTo(null);
    }
    
    public void cargarTabla(String valor){
    String [] fila = {"id", "nombre", "precio","descripcion", "categoria", "ubicacion"};
    String [] columna = new String[6];
    
    String sql = "select * from producto where nombre LIKE '%"+valor+"%'";
    
    model = new DefaultTableModel(null, fila);
    Connection con = null;
         con = getConection();
    try{
        st =  con.createStatement();
        rs = st.executeQuery(sql);
        while(rs.next()){
             columna[0]= rs.getString("id");
             columna[1]= rs.getString("nombre");
             columna[2]= rs.getString("precio");
             columna[3]= rs.getString("descripcion");
             columna[4]= rs.getString("categoria");
             columna[5]= rs.getString("ubicacion");
             model.addRow(columna);
         }
         searchtable.setModel(model);
         searchtable1.setModel(model);
         searchtable3.setModel(model);
         
    }catch(SQLException ex) {
        JOptionPane.showMessageDialog(null, ex);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_add_menu = new javax.swing.JButton();
        btn_search_menu = new javax.swing.JButton();
        btn_delete_menu = new javax.swing.JButton();
        btn_edit_menu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfiltro = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        searchtable1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtname = new javax.swing.JLabel();
        txtcost = new javax.swing.JLabel();
        txtdesc = new javax.swing.JLabel();
        namefield = new javax.swing.JTextField();
        costfield = new javax.swing.JTextField();
        descfield = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        catfield = new javax.swing.JTextField();
        ubfield = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        searchtable = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        id_del_field = new javax.swing.JTextField();
        btn_del = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        id_edit = new javax.swing.JTextField();
        btn_edit = new javax.swing.JButton();
        name_field_mod = new javax.swing.JTextField();
        cost_field_mod = new javax.swing.JTextField();
        desc_field_mod = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_save_changes = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cat_field_mod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        ub_field_mod = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchtable3 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(40, 40, 40));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_add_menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_add_menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_add_menu.setText("Agregar");
        btn_add_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_add_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        btn_search_menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_search_menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_search_menu.setText("Buscar");
        btn_search_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_search_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 73, -1));

        btn_delete_menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_delete_menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_delete_menu.setText("Eliminar");
        btn_delete_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delete_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_delete_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        btn_edit_menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_edit_menu.setForeground(new java.awt.Color(204, 204, 204));
        btn_edit_menu.setText("Editar");
        btn_edit_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 73, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menú principal");
        jLabel1.setToolTipText("");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 140, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Captura de pantalla 2021-11-20 230431.png"))); // NOI18N
        jLabel16.setMaximumSize(new java.awt.Dimension(530, 795));
        jLabel16.setMinimumSize(new java.awt.Dimension(530, 795));
        jLabel16.setPreferredSize(new java.awt.Dimension(530, 795));
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 240, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 450));

        jTabbedPane1.setBackground(new java.awt.Color(40, 40, 40));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Buscar Producto");

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Ingresa ID");

        txtfiltro.setBackground(new java.awt.Color(51, 51, 51));
        txtfiltro.setForeground(new java.awt.Color(204, 204, 204));
        txtfiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfiltroActionPerformed(evt);
            }
        });
        txtfiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtfiltroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfiltroKeyTyped(evt);
            }
        });

        searchtable1.setBackground(new java.awt.Color(102, 102, 102));
        searchtable1.setForeground(new java.awt.Color(204, 204, 204));
        searchtable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Descripcion", "Categoría", "Ubicación"
            }
        ));
        jScrollPane2.setViewportView(searchtable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, 43))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel5)
                .addGap(6, 6, 6)
                .addComponent(txtfiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Buscar", jPanel2);

        jPanel3.setBackground(new java.awt.Color(40, 40, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Agregar Producto");

        txtname.setForeground(new java.awt.Color(204, 204, 204));
        txtname.setText("Nombre");

        txtcost.setForeground(new java.awt.Color(204, 204, 204));
        txtcost.setText("Precio");

        txtdesc.setForeground(new java.awt.Color(204, 204, 204));
        txtdesc.setText("Estado");

        namefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namefieldActionPerformed(evt);
            }
        });

        btn_add.setBackground(new java.awt.Color(51, 51, 51));
        btn_add.setForeground(new java.awt.Color(204, 204, 204));
        btn_add.setText("Agregar Producto");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Categoria");

        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Ubicacion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_add))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtdesc)
                                .addComponent(jLabel11)
                                .addComponent(txtcost)
                                .addComponent(txtname)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(namefield)
                            .addComponent(costfield)
                            .addComponent(descfield, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                            .addComponent(catfield)
                            .addComponent(ubfield)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(61, 61, 61)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(costfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcost))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdesc))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(catfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ubfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(17, 17, 17)
                .addComponent(btn_add)
                .addGap(0, 122, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel3);

        jPanel4.setBackground(new java.awt.Color(40, 40, 40));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Eliminar Producto");

        searchtable.setBackground(new java.awt.Color(102, 102, 102));
        searchtable.setForeground(new java.awt.Color(204, 204, 204));
        searchtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Descripción", "Categoría", "Ubicación"
            }
        ));
        jScrollPane1.setViewportView(searchtable);

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("ID");

        id_del_field.setBackground(new java.awt.Color(51, 51, 51));
        id_del_field.setForeground(new java.awt.Color(204, 204, 204));

        btn_del.setBackground(new java.awt.Color(51, 51, 51));
        btn_del.setForeground(new java.awt.Color(204, 204, 204));
        btn_del.setText("Eliminar producto");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(id_del_field, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btn_del, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(53, 53, 53))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(id_del_field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_del)))
        );

        jTabbedPane1.addTab("Eliminar", jPanel4);

        jPanel6.setBackground(new java.awt.Color(40, 40, 40));

        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Ingresa ID");

        id_edit.setBackground(new java.awt.Color(51, 51, 51));
        id_edit.setForeground(new java.awt.Color(204, 204, 204));
        id_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_editActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(51, 51, 51));
        btn_edit.setForeground(new java.awt.Color(204, 204, 204));
        btn_edit.setText("Buscar");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        name_field_mod.setBackground(new java.awt.Color(51, 51, 51));
        name_field_mod.setForeground(new java.awt.Color(204, 204, 204));

        cost_field_mod.setBackground(new java.awt.Color(51, 51, 51));
        cost_field_mod.setForeground(new java.awt.Color(204, 204, 204));
        cost_field_mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cost_field_modActionPerformed(evt);
            }
        });

        desc_field_mod.setBackground(new java.awt.Color(51, 51, 51));
        desc_field_mod.setForeground(new java.awt.Color(204, 204, 204));

        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nombre");

        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Precio");

        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Descripción");

        btn_save_changes.setBackground(new java.awt.Color(51, 51, 51));
        btn_save_changes.setForeground(new java.awt.Color(204, 204, 204));
        btn_save_changes.setText("Guardar Cambios");
        btn_save_changes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_changesActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Categoría");

        cat_field_mod.setBackground(new java.awt.Color(51, 51, 51));
        cat_field_mod.setForeground(new java.awt.Color(204, 204, 204));

        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Ubicación");

        ub_field_mod.setBackground(new java.awt.Color(51, 51, 51));
        ub_field_mod.setForeground(new java.awt.Color(204, 204, 204));

        searchtable3.setBackground(new java.awt.Color(102, 102, 102));
        searchtable3.setForeground(new java.awt.Color(204, 204, 204));
        searchtable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Descripción", "Categoría", "Ubicación"
            }
        ));
        jScrollPane3.setViewportView(searchtable3);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Editar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(id_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit))
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(btn_save_changes)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)
                        .addComponent(jLabel7)
                        .addComponent(cat_field_mod)
                        .addComponent(desc_field_mod)
                        .addComponent(cost_field_mod)
                        .addComponent(name_field_mod)
                        .addComponent(ub_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_edit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_edit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10)
                        .addComponent(name_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addComponent(cost_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(4, 4, 4)
                .addComponent(desc_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cat_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ub_field_mod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_save_changes)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Editar", jPanel6);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, -30, -1, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_search_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_menuActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_btn_search_menuActionPerformed

    private void btn_add_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_menuActionPerformed
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_btn_add_menuActionPerformed

    private void btn_delete_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delete_menuActionPerformed
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_btn_delete_menuActionPerformed

    private void namefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namefieldActionPerformed

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
    
        Connection con = null;
        
        try{
            
            con = getConection();
            ps = con.prepareStatement("INSERT INTO producto (nombre, precio, descripcion, categoria, ubicacion) VALUES(?,?,?,?,?) ");
            ps.setString(1, namefield.getText());
            ps.setString(2, costfield.getText());
            ps.setString(3, descfield.getText());
            ps.setString(3, catfield.getText());
            ps.setString(4, ubfield.getText());
           
            
            int res = ps.executeUpdate();
            
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Producto guardado");
          
            } else {
                 JOptionPane.showMessageDialog(null, "Producto no guardado");
               
            }
            
            con.close();
            
        } catch(Exception e){
            System.err.println(e);
        }    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
         Connection con = null;
            try{
                con = getConection();
                ps = con.prepareStatement("DELETE FROM producto WHERE id=?");
                ps.setInt(1, Integer.parseInt(id_del_field.getText()));
                int res = ps.executeUpdate();
                if(res > 0){

                    JOptionPane.showMessageDialog(null, "Producto Eliminado");
                } else {

                     JOptionPane.showMessageDialog(null, "Error al eliminar producto");
                }
                con.close();
            } catch(Exception e){
            System.err.println(e);
            }
            
            cargarTabla("");
   
    }//GEN-LAST:event_btn_delActionPerformed

    
    private void txtfiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyTyped
        // TODO add your handling code here:
        
        txtfiltro.addKeyListener(new KeyAdapter(){
            @Override
            public void keyReleased(KeyEvent ke){
                
                trs.setRowFilter(RowFilter.regexFilter(txtfiltro.getText(), 1));
                trs.setRowFilter(RowFilter.regexFilter(txtfiltro.getText(), 0));
            }
        });
        trs = new TableRowSorter(model);
        searchtable1.setRowSorter(trs); 
    }//GEN-LAST:event_txtfiltroKeyTyped

    private void txtfiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiltroActionPerformed

    private void txtfiltroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfiltroKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfiltroKeyPressed

    private void btn_edit_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_menuActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_btn_edit_menuActionPerformed

    private void btn_save_changesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_changesActionPerformed
        Connection con = null;
        try{
            con = getConection();
            ps = con.prepareStatement("UPDATE producto SET  nombre=?, precio=?, descripcion=?, categoria=?, ubicacion=? WHERE id=?");
            ps.setString(1, name_field_mod.getText());
            ps.setString(2, cost_field_mod.getText());
            ps.setString(3, desc_field_mod.getText());
            ps.setString(4, cat_field_mod.getText());
            ps.setString(5, ub_field_mod.getText());
            ps.setString(6, id_edit.getText());
            int res = ps.executeUpdate();
            if(res > 0){
                JOptionPane.showMessageDialog(null, "Producto Modificado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Modificar producto");
            }
            con.close();
        } catch(Exception e){
            System.err.println(e);
        }

        cargarTabla("");
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_save_changesActionPerformed

    private void cost_field_modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cost_field_modActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cost_field_modActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        Connection con = null;

        try{
            con = getConection();
            ps = con.prepareStatement("SELECT * FROM producto WHERE id = ?");
            ps.setString(1, id_edit.getText());
            rs = ps.executeQuery();
            if(rs.next()){
                name_field_mod.setText(rs.getString("nombre"));
                cost_field_mod.setText(rs.getString("precio"));
                desc_field_mod.setText(rs.getString("descripcion"));
                cat_field_mod.setText(rs.getString("categoria"));
                ub_field_mod.setText(rs.getString("ubicacion"));
            } else {
                JOptionPane.showMessageDialog(null, "No existe el producto");
            }
        } catch(Exception e){
            System.err.println(e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void id_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainmenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainmenu().setVisible(true);
            }
        });
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_add_menu;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_delete_menu;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_edit_menu;
    private javax.swing.JButton btn_save_changes;
    private javax.swing.JButton btn_search_menu;
    private javax.swing.JTextField cat_field_mod;
    private javax.swing.JTextField catfield;
    private javax.swing.JTextField cost_field_mod;
    private javax.swing.JTextField costfield;
    private javax.swing.JTextField desc_field_mod;
    private javax.swing.JTextField descfield;
    private javax.swing.JTextField id_del_field;
    private javax.swing.JTextField id_edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField name_field_mod;
    private javax.swing.JTextField namefield;
    private javax.swing.JTable searchtable;
    private javax.swing.JTable searchtable1;
    private javax.swing.JTable searchtable3;
    private javax.swing.JLabel txtcost;
    private javax.swing.JLabel txtdesc;
    private javax.swing.JTextField txtfiltro;
    private javax.swing.JLabel txtname;
    private javax.swing.JTextField ub_field_mod;
    private javax.swing.JTextField ubfield;
    // End of variables declaration//GEN-END:variables
}
